services:
  - type: web
    name: micro-works-platform
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: microworks_production_secret_key_2024
      - key: MIN_WITHDRAWAL
        value: 500
      - key: MONGODB_URI
        sync: false
